version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - ${PORT}:${PORT}
    volumes:
    - .:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - '27017:27017'
    environment:
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB 

volumes: 
 data: {}